### ISSUE TITLE
Building obudpst for Windows

### ISSUE THREAD

**Issue by McRender** [BroadbandForum/obudpst#5]
I've been using obudpst successfully on Debian and Android based systems so far. Now I was wondering if it would be possible to have native builds for Windows as well or at least builds with a little support of Cygwin. 

Cygwin is lacking the support of `<sys/epoll.h>` but under Windows this should be negligibly. However I've been struggling come across the `if --linux--` directives in several source files. When there is no Linux system identified you include some alternative files like `../udpst_controll_alt1.h` but I could not find those within the repository. Are those files available somewhere? 

Is it even possible to build obudpst for Windows?

Would love to hear from you.

BR

**Comment by lc9892** [comment]
We're glad to hear you've been having success. In fact, we're interested in your experience with Android. What hardware did you use? Did you encounter any notable issues? Do you do any development on mobile devices?

As for Windows, yes - those `__linux__` conditionals and alt1/alt2 includes were put there to allow for the building of a Windows app with a simple GUI (although my version kept the text output). Otherwise, it reused the existing code for the actual I/O operation - essentially a wrapper. Those include files are not part of the normal repo and would be created to accommodate a non-Linux environment. The biggest change, when I did this with Visual Studio, was creation of a `udpst-win.cpp` file to take the place of `udpst.c` (for the needed Windows message loop and a few other housekeeping functions).

**Comment by McRender** [comment]
Thanks for the quick response. I've been using different kinds of modern Android based mobile devices as hardware. Main issue during building was the lack of support of OpenSSL under Android. And yes, I do development on mobile devices. 

Good to know that it "is" somehow possible to port obudpst to Windows. Managing calls to `unistd.h` `net/if.h` `netinet/in.h` `sys/epoll.h` `sys/time.h` `openssl/hmac.h` `openssl/x509.h` (and probably more) on Windows need modifications in the code on my own then. Did you encounter any significant performance differences compared to a Linux environment?

**Comment by lc9892** [comment]
Thanks for the info. My colleague and I are curious, have you given any thought to what it might take to create the client functionality on a mobile device? That's one area we haven't made any progress in...but we'd certainly like to.

As for the Windows version, the client actually performed quite well (no trouble testing 1G PON). The only consideration is that any significant interaction with the app window itself while a test is running can cause a flood of messages that may impact the max I/O rate. And regarding the additional files, I might be able to share what I have at some point if you're interested.

**Comment by McRender** [comment]
I've already managed to create a native client running on Android based mobile devices for a company internal project. If you d 'like to I could certainty establish a dialog, probably on another channel? 
Regarding the Windows version, I would personally love to have a look at those other files. Thank you for your kind offer.

**Comment by lc9892** [comment]
No problem. We're in the middle of releasing a new OB-UDPST version in the next 3-4 weeks and I'll be updating the Windows wrapper app to support the new features. We can touch base again at that time.

**Comment by McRender** [comment]
Thanks for the update, I'll close the issue and touch base again... Good luck with the new release :-)
